apiVersion: v1
kind: ConfigMap
metadata:
  name: auditd-rules
  namespace: kube-system
  labels:
    name: aks-auditd
data:
  10-procmon.rules: |
    -a exit,always -F arch=b64 -S execve -k procmon
    -a exit,always -F arch=b32 -S execve -k procmon

  